const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Loja = sequelize.define('dim_lojas', {
  id_loja: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  loja_numero: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  fantasia: { type: DataTypes.STRING(75), allowNull: false },
  loja_completo: { type: DataTypes.STRING(100), allowNull: true, validate: {} },
  razao_social: { type: DataTypes.STRING(75), allowNull: false },
  cnpj: { type: DataTypes.STRING(18), allowNull: false, unique: true },
  cnpj_s: { type: DataTypes.STRING(14), allowNull: true },
  cat: { type: DataTypes.INTEGER, allowNull: true },
  inscricao_estadual: { type: DataTypes.STRING(11), allowNull: true },
  logradouro: { type: DataTypes.STRING(50), allowNull: false },
  end_numero: { type: DataTypes.STRING(50), allowNull: false },
  end_complemento: { type: DataTypes.STRING(50), allowNull: true },
  end_bairro: { type: DataTypes.STRING(50), allowNull: false },
  cep: { type: DataTypes.STRING(10), allowNull: false },
  telefone_fixo: { type: DataTypes.STRING(15), allowNull: true },
  telefone_fixo_2: { type: DataTypes.STRING(15), allowNull: true },
  celular: { type: DataTypes.STRING(15), allowNull: true },
  fax: { type: DataTypes.STRING(15), allowNull: true },
  email: { type: DataTypes.STRING(64), allowNull: false },
  email_2: { type: DataTypes.STRING(64), allowNull: true },
  ativo: { type: DataTypes.BOOLEAN, allowNull: true },
  inaugurada: { type: DataTypes.BOOLEAN, allowNull: true },
  situacao: { type: DataTypes.SMALLINT.UNSIGNED, allowNull: true },
  responsavel: { type: DataTypes.STRING(50), allowNull: false },
  id_cidade: { type: DataTypes.INTEGER, allowNull: false },
  cidade: { type: DataTypes.STRING(100), allowNull: true },
  latitude: { type: DataTypes.DECIMAL(20, 16), allowNull: true },
  longitude: { type: DataTypes.DECIMAL(20, 16), allowNull: true },
  sistema_erp: { type: DataTypes.STRING(15), allowNull: true },
  codigo_movidesk: { type: DataTypes.STRING(100), allowNull: true },
  observacao: { type: DataTypes.STRING(255), allowNull: true },
  data_cadastro: { type: DataTypes.DATE, allowNull: true },
  data_inauguracao: { type: DataTypes.DATEONLY, allowNull: true },
  data_associacao: { type: DataTypes.DATEONLY, allowNull: true },
  data_desassociacao: { type: DataTypes.DATEONLY, allowNull: true },
  maturidade: { type: DataTypes.INTEGER, allowNull: true },
  tempo_total_associado: { type: DataTypes.STRING(50), allowNull: true },
  tempo_total_inaugurado: { type: DataTypes.STRING(50), allowNull: true },
  id_plugpharma: { type: DataTypes.INTEGER, allowNull: true },
  certificado_vencimento: { type: DataTypes.DATEONLY, allowNull: true },
  pec_ultimo_estudo: { type: DataTypes.DATEONLY, allowNull: true },
  pec_id_convenio: { type: DataTypes.STRING(5), allowNull: true },
  pec_cod_acesso: { type: DataTypes.STRING(7), allowNull: true },
  pec_app: { type: DataTypes.STRING(10), allowNull: false },
  id_grupo_empresarial: { type: DataTypes.INTEGER, allowNull: true },
  farmacia_popular: { type: DataTypes.BOOLEAN, allowNull: true },
  faturamento_inicial: { type: DataTypes.DOUBLE, allowNull: true },
  cluster: { type: DataTypes.STRING(50), allowNull: true },
  polo: { type: DataTypes.STRING(50), allowNull: true },
  gerentes_regionais: { type: DataTypes.STRING(50), allowNull: true },
  atendente: { type: DataTypes.STRING(50), allowNull: true },
  analista: { type: DataTypes.STRING(50), allowNull: true },
  cod_utc: { type: DataTypes.STRING(10), allowNull: true },
  utc: { type: DataTypes.STRING(50), allowNull: true },
  utc_pdvs: { type: DataTypes.INTEGER, allowNull: true },
  cod_brick: { type: DataTypes.STRING(10), allowNull: true },
  brick: { type: DataTypes.STRING(50), allowNull: true },
  brick_pdvs: { type: DataTypes.INTEGER, allowNull: true },
  ultima_atualizacao: { type: DataTypes.DATE, allowNull: false }
}, {
  tableName: 'dim_lojas',
  timestamps: false,
});

module.exports = Loja;
